SEED_QUESTIONS = [
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the capital city of Japan?",
    "answer": "Tokyo",
    "options": ["Tokyo", "Osaka", "Kyoto", "Seoul"],
    "explanation": "Tokyo is the capital of Japan and one of the world's largest cities.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which planet is known as the Red Planet?",
    "answer": "Mars",
    "options": ["Mars", "Venus", "Jupiter", "Mercury"],
    "explanation": "Mars appears reddish because of iron oxide on its surface.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which instrument is famous for having 88 keys?",
    "answer": "Piano",
    "options": ["Piano", "Violin", "Trumpet", "Flute"],
    "explanation": "A standard modern piano has 88 keys.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which is the largest ocean on Earth?",
    "answer": "Pacific Ocean",
    "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
    "explanation": "The Pacific Ocean is the largest and deepest ocean on Earth.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the chemical symbol for gold?",
    "answer": "Au",
    "options": ["Au", "Ag", "Gd", "Go"],
    "explanation": "The symbol Au comes from the Latin word for gold, aurum.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Who painted the Mona Lisa?",
    "answer": "Leonardo da Vinci",
    "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
    "explanation": "Leonardo da Vinci painted the Mona Lisa during the Italian Renaissance.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which country has a maple leaf on its flag?",
    "answer": "Canada",
    "options": ["Canada", "Australia", "New Zealand", "Ireland"],
    "explanation": "The red maple leaf is the central symbol on the Canadian flag.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the main language spoken in Brazil?",
    "answer": "Portuguese",
    "options": ["Portuguese", "Spanish", "French", "English"],
    "explanation": "Brazil was colonized by Portugal, so Portuguese is its official language.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which animal is the fastest on land?",
    "answer": "Cheetah",
    "options": ["Cheetah", "Lion", "Greyhound", "Gazelle"],
    "explanation": "Cheetahs can reach speeds of around 100 to 120 kilometers per hour in short bursts.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Who wrote the Harry Potter series?",
    "answer": "J. K. Rowling",
    "options": ["J. K. Rowling", "Suzanne Collins", "Roald Dahl", "Philip Pullman"],
    "explanation": "J. K. Rowling wrote the seven main Harry Potter novels.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which gas makes up most of Earth's atmosphere?",
    "answer": "Nitrogen",
    "options": ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"],
    "explanation": "Earth's atmosphere is about 78 percent nitrogen.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the world's largest hot desert?",
    "answer": "Sahara",
    "options": ["Sahara", "Gobi", "Kalahari", "Arabian"],
    "explanation": "The Sahara is the largest hot desert in the world.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What currency is used in Japan?",
    "answer": "Yen",
    "options": ["Yen", "Won", "Dollar", "Peso"],
    "explanation": "Japan's national currency is the yen.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which organ pumps blood around the human body?",
    "answer": "Heart",
    "options": ["Heart", "Liver", "Lung", "Kidney"],
    "explanation": "The heart is the muscular organ that circulates blood through the body.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the tallest mammal on Earth?",
    "answer": "Giraffe",
    "options": ["Giraffe", "Elephant", "Camel", "Moose"],
    "explanation": "Giraffes are the tallest living mammals thanks to their long legs and necks.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which ocean lies between Africa and Australia?",
    "answer": "Indian Ocean",
    "options": ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Southern Ocean"],
    "explanation": "The Indian Ocean sits between Africa, Asia, Australia, and Antarctica.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which chess piece moves in an L-shape?",
    "answer": "Knight",
    "options": ["Knight", "Bishop", "Rook", "Queen"],
    "explanation": "The knight moves two squares in one direction and one square at a right angle.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which planet is best known for its rings?",
    "answer": "Saturn",
    "options": ["Saturn", "Uranus", "Neptune", "Mars"],
    "explanation": "Saturn's ring system is the most prominent in our solar system.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is H2O more commonly known as?",
    "answer": "Water",
    "options": ["Water", "Salt", "Oxygen", "Hydrogen"],
    "explanation": "H2O is the chemical formula for water.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "Which continent is Egypt part of?",
    "answer": "Africa",
    "options": ["Africa", "Asia", "Europe", "South America"],
    "explanation": "Egypt is located in northeastern Africa.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What do bees collect from flowers to help make honey?",
    "answer": "Nectar",
    "options": ["Nectar", "Pollen", "Sap", "Dew"],
    "explanation": "Bees gather nectar from flowers and transform it into honey.",
  },
  {
    "topic": "general",
    "question_type": "multiple_choice",
    "prompt": "What is the capital city of New Zealand?",
    "answer": "Wellington",
    "options": ["Wellington", "Auckland", "Christchurch", "Hamilton"],
    "explanation": "Wellington is New Zealand's capital city.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: Lightning is hotter than the surface of the sun.",
    "answer": "True",
    "explanation": "A lightning bolt can briefly reach temperatures hotter than the surface of the sun.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: Bats are blind.",
    "answer": "False",
    "explanation": "Bats can see, and many species also use echolocation to navigate.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: Mount Kilimanjaro is in Kenya.",
    "answer": "False",
    "explanation": "Mount Kilimanjaro is in Tanzania, near the Kenyan border.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: An octopus has three hearts.",
    "answer": "True",
    "explanation": "Octopuses have three hearts and blue blood.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: The Pacific Ocean is smaller than the Atlantic Ocean.",
    "answer": "False",
    "explanation": "The Pacific Ocean is larger than the Atlantic Ocean.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: William Shakespeare wrote Romeo and Juliet.",
    "answer": "True",
    "explanation": "Romeo and Juliet is one of Shakespeare's most famous plays.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: The average healthy adult human has 206 bones.",
    "answer": "True",
    "explanation": "A typical adult human skeleton has 206 bones.",
  },
  {
    "topic": "general",
    "question_type": "true_false",
    "prompt": "True or False: Venus is the closest planet to the Sun.",
    "answer": "False",
    "explanation": "Mercury is the closest planet to the Sun.",
  },
]
